.gitignore, build.gradle, src/main/java/sekwah/mods/narutomod/NarutoMod.java, src/main/java/sekwah/mods/narutomod/client/JutsuClient.java, src/main/java/sekwah/mods/narutomod/client/NarutoKeyHandler.java, src/main/java/sekwah/mods/narutomod/client/PlayerClientTickEvent.java, src/main/java/sekwah/mods/narutomod/command/CommandJutsu.java, src/main/java/sekwah/mods/narutomod/common/JutsuCommon.java, src/main/java/sekwah/mods/narutomod/jutsu/Jutsu.java, src/main/java/sekwah/mods/narutomod/jutsu/JutsuManager.java, src/main/java/sekwah/mods/narutomod/jutsu/Jutsus.java, src/main/java/sekwah/mods/narutomod/packets/clientbound/ClientJutsuCommandPacket.java, src/main/resources/assets/narutomod/lang/en_US.lang
parts of this is a horrible hack, but it'll work until jutsu verification is moved to the server
=> add jutsu command and fix server error for invalid earth wall

src/main/resources/assets/narutomod/lang/ru_RU.lang
I have redid all russian translation and added it for new things.
=> Updated ru_RU.lang (Better translation)

src/main/resources/assets/narutomod/lang/ru_RU.lang
Music Disc changed from "Музыкальная пластинка" to "Пластинка" like in simple Minecraft. And Earth Wall from "Земленной шар" to "Земляная стена". Also fixed grammar.
=> Fixed Music Disc and Earth Wall translations

src/main/resources/assets/narutomod/lang/ru_RU.lang
Fixed grammar.
Added translation:
* Fabrics
* Naruto Kid Armour
Fixed a lot of old  translations
=> Fixed grammar. Added translation for new things. Fixed old.

src/main/resources/assets/narutomod/lang/ru_RU.lang
Changed puppet name from "Кукла" to "Марионетка"
Changed flak jacket name from "Одноцветный жилет" to "Бронированный жилет"
Changed YouTuber handbag lore from "Деревня спрятанная в мемах" to "Деревня скрытая в мемах"
=> Fixed puppet, flak jacket, names and YouTuber handbag lore.

src/main/resources/assets/narutomod/lang/ru_RU.lang
Added Learnt word localization: "Выучено!"
=> Added Learnt word localization

src/main/resources/assets/narutomod/lang/ru_RU.lang
Fixed Jonin Armour from "Жилет Джонина" to "Бронированный жилет", like in the new en_EN.land update
Changed Naruto Kid Amour translation key position to 89 string
=> Fixed Jonin Armour name and Naruto Kid Armour position

src/main/resources/assets/narutomod/lang/ru_RU.lang
Translated The Rainbow Headband to "Повязка деревни скрытой в Любви"
=> Added translation for Rainbow Headband

src/main/resources/assets/narutomod/lang/ru_RU.lang
Added translation for Mod Page button: "Страница мода"
=> Added translation for Mod Page button

src/main/resources/assets/narutomod/lang/ru_RU.lang
Translated a bunch of headbands
* Blanks
* Leaf
* Sand
* Sound
* Pride
* Rock
And more
=> Translated a bunch of headbands

src/main/resources/assets/narutomod/lang/ru_RU.lang
Added a translations for Mist, Cloud, Rain and Grass headbands.
Added a translation for Naruto Headbands creative tab
Fixed grammar (space missing) on 51 string
=> Added a translation for new headbands. Fixed grammar.

src/main/resources/assets/narutomod/lang/ru_RU.lang
Adeed a translation for Jutsu Skill Tree and Sakura Bonsai. 
Fixed the Earh-Wall judsu error message.
=> Added a translation for 2 new things and retranslated the old one

src/main/java/sekwah/mods/narutomod/NarutoMod.java, src/main/java/sekwah/mods/narutomod/assets/JutsuData.java, src/main/java/sekwah/mods/narutomod/client/JutsuClient.java
note: client still has full control over the config, needs to be reworked at some point
=> added basic config

src/main/resources/assets/narutomod/lang/ru_RU.lang
Added Russian translation for Kakashi Armour and Han's Hat
=> Added Russian translation for new things

src/main/resources/assets/narutomod/lang/ru_RU.lang
Created Russian translation for Planetary Devastation jutsu :3
=> Created new Russian translation :3

src/main/resources/assets/narutomod/lang/ru_RU.lang
Fully recreated Russian translation
Fixed:
- Grammar errors
- Incorrect translation
Added:
- Translation for many new things
=> Created Russian Translation 2.0

src/main/resources/assets/narutomod/lang/ru_ru.json
Created Russian translation for the **Naruto Mod 1.16**
=> Created ru_ru.json

src/main/java/com/sekwah/narutomod/capabilities/NinjaCapabilityHandler.java, src/main/java/com/sekwah/narutomod/capabilities/NinjaData.java, src/main/java/com/sekwah/narutomod/client/gui/ChakraAndStaminaGUI.java, src/main/java/com/sekwah/narutomod/config/NarutoConfig.java, src/main/java/com/sekwah/sekclib/SekCLib.java, src/main/java/com/sekwah/sekclib/capabilitysync/SyncEntry.java, src/main/java/com/sekwah/sekclib/capabilitysync/capability/SyncDataCapabilityHandler.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/CapabilitySyncRegistry.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/RegisterSyncTrackerTypeEvent.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/annotation/Sync.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/broadcaster/CapabilityBroadcaster.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/broadcaster/CapabilityInfo.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/tracker/ISyncTrackerData.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/tracker/SyncTracker.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/tracker/SyncTrackerData.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/tracker/SyncTrackerFactory.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/tracker/SyncTrackerSerializer.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/tracker/implemented/BaseSyncTrackers.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/tracker/implemented/FloatSyncTracker.java, src/main/java/com/sekwah/sekclib/capabilitysync/capabilitysync/tracker/implemented/IntSyncTracker.java, src/main/java/com/sekwah/sekclib/network/SekCPacketHandler.java, src/main/java/com/sekwah/sekclib/network/s2c/ClientCapabilitySyncPacket.java
Should squash merge this though will do all the logic for packet syncing here
=> feat: Add start of capability sync packets

README.md
📦 Published PR to [discord](https://discord.sekwah.com/) as canary version: <code>1.1.0--canary.131.2d91c79</code>
=> fix: For some reason the latest version didn't properly release

src/main/java/com/sekwah/narutomod/abilities/utility/WaterWalkAbility.java
📦 Published PR to [discord](https://discord.sekwah.com/) as canary version: <code>1.2.0--canary.133.d5306e2</code>
=> fix: stop water walking on solid waterlogged blocks
